### PR TITLE
isValid modified

### PR DESCRIPTION
**Pull request by gremrok**
it works for me now

### CODE REVIEW

**Comment by suevalov** [comment]
@gremrok Could you describe what was wrong with the initial implementation and how your change fixes it?

**Comment by gremrok** [comment]
when I'm trying validate an attribute, calls method 
`validateAttr = function (masterDeferred, model, attr, value, computed)`
and some arguments are wrong (`masterDeferred`becomes a model and `masterDeferred.resolve();` not worked, `resolve` is `undefined`).
In my solution I call in `isValid`method `validateAttr` with correct arguments, and return later `true` or `false`, whichever `resolve` or `reject` was called.
But `isValid(true)` still not working for me. First I'm trying to validate _invalid_ model and become `model._isValid == false`, that is correct. Second I'm trying to validate _valid_ model and `option` is true,
calls method `validate()`, but `isValid` return me old value `_isValid`, that is false, and new value is not yet calculated. So I become invalid form in my view, but model is valid.

**Comment by suevalov** [comment]
thanks for fixing it

**Comment by gremrok** [comment]
can be used `flattened[attr]`instead `this.attributes[attr]`.
And what is in case 'option === true'?

**Pull request merged**
